name: jumo
root: ~/jumo/

windows:
  - editor:
      layout: even-horizontal
      panes:
        - poetry run nvim
  - servers:
      layout: even-horizontal
      panes:
        - cd ~/jumo/jumo_cli && cargo run
        - poetry run fastapi dev jumo_server/main.py --host 10.0.0.37 --port 8000
  - dbs:
      layout: even-horizontal
      panes:
        - docker-compose up
