[tool.poetry]
name = "jumo"
version = "0.1.0"
description = ""
authors = ["ryan-m-walker <ryan.matthew.walker@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
anthropic = "^0.42.0"
openai = "^1.59.4"
fastapi = {extras = ["standard"], version = "^0.115.6"}
bson = "^0.5.10"
pymongo = "^4.10.1"
qdrant-client = "^1.12.2"
load-dotenv = "^0.1.0"
mem0ai = {extras = ["graph"], version = "^0.1.40"}
neo4j = "^5.27.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
